CREATE TABLE "Pothole_Data_for_Flywheel_010123_090725_1" (
    "SR_NUMBER" VARCHAR(255) PRIMARY KEY,
    "SR_STATUS" VARCHAR(255),
    "SR_STATUS_FLAG" VARCHAR(255),
    "SR_TYPE_DESC" VARCHAR(255),
    "ADDRESS" VARCHAR(255),
    "LOCATION" VARCHAR(255),
    "DATE_CREATED" TIMESTAMP,
    "PLANNED_END_DATE" TIMESTAMP,
    "DATE_CLOSED" TIMESTAMP,
    "Closed by Planned End Date" VARCHAR(255),
    "STREET_DIRECTION" VARCHAR(255),
    "STREET_NO" VARCHAR(255),
    "STREET_NAME" VARCHAR(255),
    "ZIPCODE" VARCHAR(20),
    "NUM_POTHOLES" INTEGER,
    "METHOD_RECEIVED" VARCHAR(255),
    "NEIGHBORHOOD" VARCHAR(255),
    "SNA_NEIGHBORHOOD" VARCHAR(255),
    "CC_NEIGHBORHOOD" VARCHAR(255),
    "LATITUDE" DECIMAL,
    "LONGITUDE" DECIMAL,
    "X_COORD" DECIMAL,
    "Y_COORD" DECIMAL
);

CREATE TABLE "MostPotHoleNeiYear" (
    "id" VARCHAR(255) PRIMARY KEY,
    "NEIGHBORHOOD" VARCHAR(255),
    "yearCreated" INTEGER,
    "totPotHole" INTEGER
);

CREATE TABLE "MostPotHolesNei" (
    "id" VARCHAR(255) PRIMARY KEY,
    "NEIGHBORHOOD" VARCHAR(255),
    "TotNumPot" INTEGER
);

CREATE TABLE "MostPotHolesST" (
    "id" VARCHAR(255) PRIMARY KEY,
    "STREET_NAME" VARCHAR(255),
    "totPotHole" INTEGER
);

CREATE TABLE "MostPotHolesSTNei" (
    "id" VARCHAR(255) PRIMARY KEY,
    "NEIGHBORHOOD" VARCHAR(255),
    "STREET_NAME" VARCHAR(255),
    "TotNumPot" INTEGER
);

CREATE TABLE "MostPotHolesSTYear" (
    "id" VARCHAR(255) PRIMARY KEY,
    "STREET_NAME" VARCHAR(255),
    "yearCreated" INTEGER,
    "totPotHole" INTEGER
);
